### ISSUE TITLE
Failed to reserve TZ/FW region

### ISSUE THREAD

**Issue by haidzkek** [SoMainline/linux-apple-resources#21]
i have an iPhone 6 plus on 12.5.5, i compiled pongoOS and the kernel, but when i boot the thing, it gives an error saying "Failed to reserve TZ/FW region" and "panic: booting Linux failed!" before booting into stock iOS

i am running ubuntu 22.04, did i compile the kernel wrong?
![IMG_0340](https://github.com/SoMainline/linux-apple-resources/assets/111658941/f97ff915-4798-494c-85b2-0740dd64fc8b)
![IMG_0339](https://github.com/SoMainline/linux-apple-resources/assets/111658941/dd0754a8-bd76-49b6-b126-2eaf0e2448b9)

**Comment by haidzkek** [comment]
i have also downloaded the pull request here: https://github.com/konradybcio/pongoOS/pull/4/files yet the probelm still persists

**Comment by haidzkek** [comment]
closed, i messed up when i compiled the kernel

**Comment by merll002** [comment]
I am having this issue as well, how did you fix it?
